name: Deploy to GitHub Pages

permissions:
  contents: write
  pull-requests: write 
  deployments: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
