name: Deploy to GitHub Pages

permissions:
  contents: write
  pull-requests: write 
  deployments: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x' 

      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release --base-href="/web_cache/"

      - name: Move files and update index.html
        run: |
          VERSION="web_12345"
          mkdir build/deploy
          mv build/web "build/deploy/$VERSION"
          mv "build/deploy/$VERSION/index.html" "build/deploy/index.html"
          sed -i 's|<head>|<head><base href="./'"$VERSION"'/">|' build/deploy/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/deploy
