name: Deploy to GitHub Pages

permissions:
  contents: write
  pull-requests: write 
  deployments: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x' 

      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release  --base-href="/web_cache/" --web-renderer=canvaskit

      - name: Get the last commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update flutter_bootstrap.js with commit hash in index.html
        working-directory: build/web
        run: |
          COMMIT_HASH=${{ env.COMMIT_HASH }}
          sed -i "s|flutter_bootstrap.js|flutter_bootstrap.js?cache_bust=${COMMIT_HASH}|" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
